# Generated by Django 4.2.5 on 2023-10-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Davinci002_Query_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_prompt', models.CharField()),
                ('prompt', models.CharField()),
                ('post_prompt', models.CharField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
