# Generated by Django 4.2.5 on 2023-10-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='davinci002_query_log',
            name='response',
            field=models.CharField(null=True),
        ),
    ]
