# Generated by Django 4.2.5 on 2023-10-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectfield_alter_project_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='download_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_zip',
            field=models.FileField(upload_to='media/portfolio_code_zipped/'),
        ),
    ]
