# Generated by Django 4.2.5 on 2023-10-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_download_url_alter_project_code_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='download_url',
            new_name='code_download_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='code_zip',
        ),
    ]
