# Generated by Django 4.2.5 on 2023-10-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_field_project_project_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfield',
            old_name='project_field',
            new_name='field',
        ),
    ]
